layout_spectrum: 0.2470520786009729
typography_spectrum: 0.3185571550857276
color:
  brandStrength: 0.3888873558025807
  lightness: 0.6931688499171287
  saturation: 0.800015636254102
  rhythmicContrast: 0.2457124670036137
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
name: levelb
